trigger:
  none

resources:
  - repo: self

variables:
  netcoresdk_version: "10.0.102"
  version: 0.0.0.1
  docker_registry: something
  docker_repo: something
  tag: $(version)

stages:
- stage: Build
  displayName: Build
  jobs:
    - job: DockerBuildLinux
      displayName: DockerBuild - Linux
      pool:
        vmImage: "ubuntu-22.04"
      steps:
        - task: UseDotNet@2
          displayName: Install .NET Core SDK v$(netcoresdk_version)
          inputs:
            packageType: sdk
            version: $(netcoresdk_version)
        
        - task: DotNetCoreCLI@2
          displayName: Publish
          inputs:
            command: publish
            projects: Rnwood.Smtp4dev/Rnwood.Smtp4dev.csproj
            publishWebProjects: false
            zipAfterPublish: false
            modifyOutputPath: false
            arguments: '-c Release -p:version=$(version) -o out'
        - task: Docker@2
          displayName: Build image
          inputs:
            command: build
            dockerfile: "**/Dockerfile.linux"
            arguments: "--build-arg version=$(version) -t $(docker_repo):linux-amd64-$(tag)"
   
- stage: Release
  dependsOn: 
  - Build
  displayName: Release
  jobs:
    - job: Release
      pool:
        vmImage: "ubuntu-22.04"
      steps:
        - checkout: none
        - task: DownloadPipelineArtifact@2
          inputs:
            path: $(Build.ArtifactStagingDirectory)
            
    - job: DockerReleaseTagLinux
      displayName: Docker Release Tag - Linux
      variables:
        DOCKER_CLI_EXPERIMENTAL: enabled
      pool:
        vmImage: "ubuntu-22.04"
      steps:
        - checkout: none
        - task: Docker@2
          displayName: Login.
          inputs:
            containerRegistry: $(docker_registry)
            repository: $(docker_repo)
            command: login
        - task: PowerShell@2
          displayName: Tag release
          inputs:
            targetType: inline
            script: | 
              docker pull $(docker_repo):linux-amd64-$(tag)

              docker tag $(docker_repo):linux-amd64-$(tag) $(docker_repo):linux-amd64-$_
              docker push $(docker_repo):linux-amd64-$_
